export const courseTypes = [
    'Main course',
    'Side dish',
    'Dessert',
    'Appetizer',
    'Salad',
    'Bread',
    'Breakfast',
    'Soup',
    'Beverage',
    'Sauce',
    'Marinade',
    'Fingerfood',
    'Snack',
    'Drink',
    'All',
];

export const dietTypes = [
    'Gluten free',
    'Ketogenic',
    'Lacto vegetarian',
    'Ovo vegetarian',
    'Vegan',
    'Pescetarian',
    'Paleo',
    'Primal',
    'Low fodmap',
    'Whole30',
];

export const cousineTypes = [
    'African',
    'American',
    'British',
    'Cajun',
    'Caribbean',
    'Chinese',
    'Eastern European',
    'European',
    'French',
    'German',
    'Greek',
    'Indian',
    'Irish',
    'Italian',
    'Japanese',
    'Jewish',
    'Korean',
    'Latin American',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'Southern',
    'Spanish',
    'Thai',
    'Vietnamese',
];

export const maxReadyTimes = [15, 30, 45, 60, 90, 120, 180];
