export const courseTypes = {
    'Main course': 'maincourse',
    'Side dish': 'sidedish',
    Dessert: 'dessert',
    Appetizer: 'appetizer',
    Salad: 'salad',
    Bread: 'bread',
    Breakfast: 'breakfast',
    Soup: 'soup',
    Beverage: 'beverage',
    Sauce: 'sauce',
    Marinade: 'marinade',
    Fingerfood: 'fingerfood',
    Snack: 'snack',
    Drink: 'drink',
    All: 'all',
};

export const dietTypes = {
    'Gluten free': 'glutenfree',
    Ketogenic: 'ketogenic',
    'Lacto vegetarian': 'lactovegetarian',
    'Ovo vegetarian': 'ovovegetarian',
    Vegan: 'vegan',
    Pescetarian: 'pescetarian',
    Paleo: 'paleo',
    Primal: 'primal',
    'Low fodmap': 'lowfodmap',
    Whole30: 'whole30',
    All: 'all',
};

export const cuisineTypes = {
    African: 'African',
    American: 'American',
    British: 'British',
    Cajun: 'Cajun',
    Caribbean: 'Caribbean',
    Chinese: 'Chinese',
    'Eastern European': 'Eastern European',
    European: 'European',
    French: 'French',
    German: 'German',
    Greek: 'Greek',
    Indian: 'Indian',
    Irish: 'Irish',
    Italian: 'Italian',
    Japanese: 'Japanese',
    Jewish: 'Jewish',
    Korean: 'Korean',
    'Latin American': 'Latin American',
    Mediterranean: 'Mediterranean',
    Mexican: 'Mexican',
    'Middle Eastern': 'Middle Eastern',
    Nordic: 'Nordic',
    Southern: 'Southern',
    Spanish: 'Spanish',
    Thai: 'Thai',
    Vietnamese: 'Vietnamese',
    All: 'all',
};

export const maxReadyTimes = [15, 30, 45, 60, 90, 120, 180];
